(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},g=ba(this),n;
if("function"==typeof Object.setPrototypeOf)n=Object.setPrototypeOf;else{var p;a:{var ca={a:!0},r={};try{r.__proto__=ca;p=r.a;break a}catch(a){}p=!1}n=p?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var t=n,u=this||self,v=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},w=function(a,b){function c(){}c.prototype=b.prototype;a.sa=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.wa=function(d,e,k){for(var h=Array(arguments.length-2),f=2;f<arguments.length;f++)h[f-2]=arguments[f];return b.prototype[e].apply(d,h)}},x=function(a){return a};var y=function(a,b){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=1);return a},A=function(a,b,c){a=z(a,b,c);return 0<a?a:c},z=function(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a},B=function(a,b,c){return a.hasAttribute(b)?a.getAttribute(b):c};var E=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d};var F=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")},da=function(a){if(F(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&F(a))return a;return null},G=function(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)},H=function(a,b){return(a=B(a,b,""))?a.split(",").map(function(c){return c.trim()}):[]};function I(a){if(Error.captureStackTrace)Error.captureStackTrace(this,I);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}w(I,Error);I.prototype.name="CustomError";var J=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");I.call(this,c+a[d])};w(J,I);J.prototype.name="AssertionError";
var K=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var k=d}else a&&(e+=": "+a,k=b);throw new J(""+e,k||[]);},L=function(a,b,c){a||K("",null,b,Array.prototype.slice.call(arguments,2));return a},M=function(a,b){throw new J("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},ea=function(a,b,c){"string"!==typeof a&&K("Expected string but got %s: %s.",[v(a),a],b,Array.prototype.slice.call(arguments,2))};var N;var P=function(a,b){this.W=a===fa&&b||"";this.ka=ha};P.prototype.S=!0;P.prototype.R=function(){return this.W};P.prototype.toString=function(){return"Const{"+this.W+"}"};var ia=function(a){if(a instanceof P&&a.constructor===P&&a.ka===ha)return a.W;M("expected object of type Const, got '"+a+"'");return"type_error:Const"},ha={},fa={};var Q=function(a,b){this.U=b===ja?a:""};Q.prototype.S=!0;Q.prototype.R=function(){return this.U.toString()};Q.prototype.toString=function(){return this.U.toString()};var ka=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,ja={};var R=function(a,b,c){this.T=c===la?a:""};R.prototype.S=!0;R.prototype.R=function(){return this.T.toString()};R.prototype.toString=function(){return this.T.toString()};var la={};var ma=function(a,b,c,d){var e=new XMLHttpRequest;e.open("GET",b);e.setRequestHeader("Content-Type","image/svg+xml");e.addEventListener("load",function(){var k=e.responseText,h=new DOMParser;var f=new P(fa,"Uses attributes only.");ea(ia(f),"must provide justification");L(!/^[\s\xa0]*$/.test(ia(f)),"must provide non-empty justification");if(void 0===N){f=null;var l=u.trustedTypes;if(l&&l.createPolicy)try{f=l.createPolicy("goog#html",{createHTML:x,createScript:x,createScriptURL:x})}catch(q){u.console&&
u.console.error(q.message)}N=f}k=(f=N)?f.createHTML(k):k;f=new R(k,null,la);k=h.parseFromString;f instanceof R&&f.constructor===R?f=f.T:(M("expected object of type SafeHtml, got '"+f+"' of type "+v(f)),f="type_error:SafeHtml");if(h=k.call(h,f,"image/svg+xml").getElementsByTagName("svg")[0])if(h.hasAttribute("width")&&h.hasAttribute("height"))a.src=b;else{k=c;f=d;if(l=h.getAttribute("viewBox")){var m=l.match(/[\d,\.]+ [\d,\.]+ ([\d,\.]+) ([\d,\.]+)/);m&&(l=parseFloat(m[1]),m=parseFloat(m[2]),l&&m&&
(f=Math.min(c/l,d/m),k=l*f,f*=m))}h.setAttribute("width",k);h.setAttribute("height",f);h=(new XMLSerializer).serializeToString(h);a.src="data:image/svg+xml;base64,"+window.btoa(h)}});e.send()};var na="gwd-blinds gwd-door-wipe gwd-fade gwd-iris-wipe gwd-push gwd-radial-wipe gwd-rotate gwd-slice gwd-split-push gwd-stripe-wipe gwd-venetian-blinds gwd-wipe gwd-zigzag".split(" ");var oa=["easing","exit-urls","scaling","transition-duration"],S=function(){var a=HTMLElement.call(this)||this;a.B=[];a.v=[];a.I=a.ma.bind(a);a.F=!1;a.da=0;a.h=0;a.Y=null;a.s=null;a.L=null;a.O=0;a.u=0;a.H=!1;a.G=!1;a.o=null;a.fa=a.na.bind(a);a.ia=a.qa.bind(a);a.ha=a.pa.bind(a);a.ga=a.oa.bind(a);a.N=!1;a.m=!1;a.canvas=null;a.A=null;a.ea=!1;return a},T=HTMLElement;S.prototype=aa(T.prototype);S.prototype.constructor=S;
if(t)t(S,T);else for(var U in T)if("prototype"!=U)if(Object.defineProperties){var pa=Object.getOwnPropertyDescriptor(T,U);pa&&Object.defineProperty(S,U,pa)}else S[U]=T[U];S.sa=T.prototype;
S.prototype.connectedCallback=function(){var a=this;this.l=this.clientWidth;this.i=this.clientHeight;var b=z(this,"swipe-committed-threshold",.25);this.ta=b*this.l;this.ua=b*this.i;this.va=z(this,"swipe-threshold",.3);this.J=H(this,"images");this.M=y(this,"start-frame");this.X=1E3*A(this,"transition-duration",1);this.la=1E3*A(this,"autoplay-frame-interval",1.5);this.Z=y(this,"autoplay-loop-count");this.ja=this.hasAttribute("wrap");this.K=B(this,"scaling","stretch");this.ba=B(this,"easing","linear");
this.D=B(this,"gesture","click");this.P=this.hasAttribute("enable-interactive-transition");this.ra=this.hasAttribute("ignore-reverse-swipe");this.ca=H(this,"exit-urls");setTimeout(function(){a.j=a.firstElementChild&&-1!==na.indexOf(a.firstElementChild.tagName.toLowerCase())?a.firstElementChild:null;a.hasAttribute("has-navigation")&&!a.o&&(a.i-=36,a.o=a.ownerDocument.createElement("gwd-gallerynavigation"),a.o.setAttribute("for",a.id),a.appendChild(a.o),G(a,"navigation-highlight",a.o,"highlight"),G(a,
"navigation-thumbnails",a.o,"use-thumbnails"));a.canvas||(a.canvas=a.ownerDocument.createElement("canvas"),a.appendChild(a.canvas));qa(a,a.canvas);a.$=a.canvas.getBoundingClientRect();a.aa=a.canvas.getContext("2d");a.A||(a.A=a.ownerDocument.createElement("gwd-gesture"),a.appendChild(a.A));var c=a.A;c.addEventListener("tap",a.fa,!1);if("swipe"===a.D||"click"===a.D&&a.P)c.addEventListener("trackstart",a.ia,!1),c.addEventListener("track",a.ha,!1),c.addEventListener("trackend",a.ga,!1);a.ea=!0;a.gwdIsLoaded()||
((c=da(a))?c.gwdIsLoaded()&&a.gwdLoad():a.gwdLoad())},0)};S.prototype.disconnectedCallback=function(){if(this.A){var a=this.A;a.removeEventListener("tap",this.fa,!1);if("swipe"===this.D||"click"===this.D&&this.P)a.removeEventListener("trackstart",this.ia,!1),a.removeEventListener("track",this.ha,!1),a.removeEventListener("trackend",this.ga,!1)}this.o&&(this.removeChild(this.o),this.o=null)};
S.prototype.attributeChangedCallback=function(a){if(this.F)switch(a){case "transition-duration":this.X=1E3*A(this,"transition-duration",1);break;case "easing":this.ba=B(this,"easing","linear");break;case "scaling":this.K=B(this,"scaling","stretch");ra(this);V(this,this.g,!1);break;case "exit-urls":this.ca=H(this,"exit-urls")}};
S.prototype.gwdLoad=function(){if(!this.F||this.ea)if(this.da=0,this.J.length)for(var a=0;a<this.J.length;a++){var b=this.ownerDocument.createElement("img");b.addEventListener("load",this.I,!1);b.addEventListener("error",this.I,!1);var c=this.J[a];"svg"===c.split(".").pop().toLowerCase()?ma(b,c,this.l,this.i):b.src=c;this.B.push(b)}else this.F=!0,E("ready",this)};S.prototype.gwdIsLoaded=function(){return this.F};
var qa=function(a,b){var c=window.devicePixelRatio;b.width=a.l*c;b.height=a.i*c;b.style.width=a.l+"px";b.style.height=a.i+"px";b.getContext("2d").scale(c,c)};S.prototype.ma=function(a){var b=a.target;b.removeEventListener("load",this.I,!1);b.removeEventListener("error",this.I,!1);b=this.B.indexOf(b);0<=b&&("error"===a.type&&this.B.splice(b,1),++this.da==this.J.length&&(ra(this),this.hasAttribute("autoplay")?this.startAutoplay():this.goToFrame(this.M,!1),this.F=!0,E("ready",this)))};
S.prototype.getFrame=function(a){if(0!=this.h)return this.B[a-1]};S.prototype.goToFrame=function(a,b){b=void 0===b?!!this.j:b;this.stop(!1);this.h&&(a=sa(this,a),a!=this.g&&V(this,a,b))};
var V=function(a,b,c){c=void 0===c?!!a.j:c;E("frameactivated",a,{id:b+1});c?(a.C=b,a.Y=Date.now()-(a.m?a.u*a.X:0),a.m=!1,a.V()):(a.aa.clearRect(0,0,a.l,a.i),a.aa.drawImage(a.v[b],0,0,a.l,a.i),ta(a,b))},ra=function(a){a.v=[];for(var b=0;b<a.B.length;b++){var c=a.B[b],d=c.naturalWidth,e=c.naturalHeight,k=!1;d&&e||(a.appendChild(c),k=!0,d=c.width,e=c.height);var h=0,f=0,l=d,m=e,q=0,O=0,C=a.l,D=a.i;"contain"===a.K?(q=Math.min(a.l/d,a.i/e),C=q*d,D=q*e,q=(a.l-C)/2,O=(a.i-D)/2):"cover"===a.K?(h=Math.max(a.l/
d,a.i/e),l=a.l/h,m=a.i/h,h=(d-l)/2,f=(e-m)/2):"none"===a.K&&(f=d-a.l,l=e-a.i,h=Math.max(f/2,0),q=Math.max(-f/2,0),f=Math.max(l/2,0),O=Math.max(-l/2,0),l=Math.min(d,a.l),m=Math.min(e,a.i),C=l,D=m);d=a.ownerDocument.createElement("canvas");qa(a,d);d.getContext("2d").drawImage(c,h,f,l,m,q,O,C,D);a.v.push(d);k&&a.removeChild(c)}a.h=a.v.length},ta=function(a,b){a.g!=b&&(a.g=b,E("frameshown",a,{frameIndex:a.g}),0==a.g?E("reachleftend",a):a.g==a.h-1&&E("reachrightend",a))};
S.prototype.goForwards=function(){this.stop(!1);(this.ja||this.g!=this.h-1)&&this.h&&V(this,W(this,!0))};S.prototype.goBackwards=function(){this.stop(!1);(this.ja||0!=this.g)&&this.h&&V(this,W(this,!1))};var W=function(a,b){return((b?a.g+1:a.g-1)+a.h)%a.h},sa=function(a,b){1>b?b=1:b>a.h&&(b=a.h);return b-1};
S.prototype.V=function(){this.m||null===this.Y||(this.u=ua(this,Math.min(1,(Date.now()-this.Y)/this.X)),this.s=requestAnimationFrame(this.V.bind(this)));this.j.renderAnimation(this.v[this.g],this.v[this.C],this.u);1!=this.u||this.m||(this.s&&(cancelAnimationFrame(this.s),this.s=null),this.j.resetDirection(),ta(this,this.C),(this.G||this.H)&&X(this))};var ua=function(a,b){switch(a.ba){case "ease-in":return b*b*b;case "ease-in-out":return 3*b*b-2*b*b*b;case "ease-out":return a=1-b,1-a*a*a;default:return b}};
S.prototype.startAutoplay=function(a){this.O=0;(void 0===a?0:a)||this.goToFrame(this.M,!1);this.G=!0;X(this)};S.prototype.rotateOnce=function(a){(void 0===a?0:a)||this.goToFrame(this.M,!1);this.H=!0;X(this)};var va=function(a){var b=sa(a,a.M);return 0==b?a.h:b};S.prototype.updateAnimationElement=function(a){this.j=a};
var X=function(a){if(a.H){if(a.g==va(a)-1){a.stop(!0);return}}else if(a.G&&0!=a.Z&&(a.g==va(a)-1&&a.O++,a.O>=a.Z)){a.stop(!0);return}a.L=setTimeout(function(){requestAnimationFrame(function(){a.h&&V(a,W(a,!0));a.j||X(a)})},a.la)},wa=function(a){.5<=a.u?V(a,a.C,!1):V(a,a.g,!1)};
S.prototype.stop=function(a,b){b=null!=b?b:!0;this.s&&(cancelAnimationFrame(this.s),this.s=null,wa(this));this.m&&(this.m=!1,wa(this),this.j.resetDirection());this.L&&(clearTimeout(this.L),this.L=null);this.H?(this.H=!1,b&&E("rotateonceended",this,{completed:!!a})):this.G&&(this.G=!1,b&&E("autoplayended",this,{completed:!!a}))};
S.prototype.na=function(){if(this.h){E("frametap",this,{id:this.g+1});var a=this.ca[this.g];if(a){if(this.stop(!1),!E("frameexit",this,{url:a}).detail.handled){a instanceof Q||a instanceof Q||(a="object"==typeof a&&a.S?a.R():String(a),L(ka.test(a),"%s does not match the safe URL pattern",a)||(a="about:invalid#zClosurez"),a=new Q(a,ja));var b=a;a=u.open;b instanceof Q&&b.constructor===Q?b=b.U:(M("expected object of type SafeUrl, got '"+b+"' of type "+v(b)),b="type_error:SafeUrl");a.call(u,b,"")}}else"click"==
this.D&&this.goForwards()}};S.prototype.qa=function(){this.stop(!1)};S.prototype.pa=function(a){var b=this;if(!this.N)if(this.P&&Y(this,a.dx,a.dy,!1)){this.m||(this.m=!0,Z(this,a.dx,a.dy,function(){b.C=W(b,!0)},function(){b.C=W(b,!1)}));a=Math.abs(a.dy)>Math.abs(a.dx)?(a.clientY-this.$.top)/this.i:(a.clientX-this.$.left)/this.l;var c=this.j.getSupportedSwipeDirection();0>c[0]+c[1]&&(a=1-a);this.u=a;this.V()}else Y(this,a.dx,a.dy,!0)&&(this.N=!0,Z(this,a.dx,a.dy,this.goForwards.bind(this),this.goBackwards.bind(this)))};
S.prototype.oa=function(a){this.N?this.N=!1:this.m?this.u>=this.va?V(this,this.C):this.stop(!1,!1):Y(this,a.dx,a.dy,!1)&&Z(this,a.dx,a.dy,this.goForwards.bind(this),this.goBackwards.bind(this))};
var Y=function(a,b,c,d){var e=Math.abs(c)>Math.abs(b),k=a.j?a.j.getSupportedSwipeDirection():[0,0];b*=k[0];c*=k[1];return(e?c:b)?a.ra&&(e?0>c:0>b)?!1:d?e?Math.abs(c)>=a.ua:Math.abs(b)>=a.ta:!0:!1},Z=function(a,b,c,d,e){Math.abs(c)>Math.abs(b)?0<c?(a.j.setDirection("toptobottom"),e()):(a.j.setDirection("bottomtotop"),d()):0<b?(a.j.setDirection("lefttoright"),e()):(a.j.setDirection("righttoleft"),d())};
g.Object.defineProperties(S.prototype,{frameCount:{configurable:!0,enumerable:!0,get:function(){return this.h}},currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.h?this.g+1:void 0}}});g.Object.defineProperties(S,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return oa}}});customElements.define("gwd-transitiongallery",S);}).call(this);
